version: 0.1
os: linux
files:
  - source: /main
    destination: /home/ubuntu/codebuildtest
hooks:
  BeforeInstall:
    - location: pkill main
      timeout: 30
      runas: root
  ApplicationStart:
    - location: main
      timeout: 300
      runas: ubuntu
